//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleTranslateIpCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Texts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Texts() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GoogleTranslateIpCheck.Properties.Texts", typeof(Texts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 未能找到 IP 文件
        ///尝试从服务器获取 IP 的本地化字符串。
        /// </summary>
        internal static string IPNotFind {
            get {
                return ResourceManager.GetString("IPNotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描完成, 找到 IP 的本地化字符串。
        /// </summary>
        internal static string IPScanCount {
            get {
                return ResourceManager.GetString("IPScanCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无可用 IP, 删除 ip(v6).txt 文件进入扫描模式 的本地化字符串。
        /// </summary>
        internal static string NoIPFile {
            get {
                return ResourceManager.GetString("NoIPFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取配置出错, 将采用默认配置 的本地化字符串。
        /// </summary>
        internal static string ReadConfigError {
            get {
                return ResourceManager.GetString("ReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取服务器 IP 失败 的本地化字符串。
        /// </summary>
        internal static string RemoteIPFail {
            get {
                return ResourceManager.GetString("RemoteIPFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///检测 IP 完毕, 按响应时间排序
        /// 的本地化字符串。
        /// </summary>
        internal static string ScanComplete {
            get {
                return ResourceManager.GetString("ScanComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否设置到 Host 文件 (Y/N) 的本地化字符串。
        /// </summary>
        internal static string SetHostConfirm {
            get {
                return ResourceManager.GetString("SetHostConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 Host 文件需管理员权限 (macOS/Linux 使用 sudo 运行), 可能会被拦截, 建议手动复制以下文本 的本地化字符串。
        /// </summary>
        internal static string SetHostTip {
            get {
                return ResourceManager.GetString("SetHostTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置成功 的本地化字符串。
        /// </summary>
        internal static string SetSuccess {
            get {
                return ResourceManager.GetString("SetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///开始检测响应时间
        /// 的本地化字符串。
        /// </summary>
        internal static string StartScan {
            get {
                return ResourceManager.GetString("StartScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扫描已开始, 时间较长请耐心等候 的本地化字符串。
        /// </summary>
        internal static string StartScanTip {
            get {
                return ResourceManager.GetString("StartScanTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支持 IPv6 请优先使用 -6 启动 的本地化字符串。
        /// </summary>
        internal static string SupportIPv6 {
            get {
                return ResourceManager.GetString("SupportIPv6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时 的本地化字符串。
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 文件路径为 /etc/hosts 的本地化字符串。
        /// </summary>
        internal static string UnixHostPath {
            get {
                return ResourceManager.GetString("UnixHostPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Host 文件路径为 %windir%\System32\drivers\etc\hosts (需去掉只读属性) 的本地化字符串。
        /// </summary>
        internal static string WinHostPath {
            get {
                return ResourceManager.GetString("WinHostPath", resourceCulture);
            }
        }
    }
}
